seems to work for cifar - need to check issue with mnist
Unconditional probability: 0.2
Starting epoch 1/2...
Traceback (most recent call last):
  File "/Users/guillaume12321/Documents/GitHub/Classifier-Free-Diffusion-Models/main.py", line 233, in <module>
    main()
  File "/Users/guillaume12321/Documents/GitHub/Classifier-Free-Diffusion-Models/main.py", line 225, in main
    train(model, emb, lr=lr, num_epochs=num_epochs, p_uncond=p_uncond, loader=data_loader, dataset_name=dataset_name, verbose=verbose)
  File "/Users/guillaume12321/Documents/GitHub/Classifier-Free-Diffusion-Models/main.py", line 110, in train
    model_out = model(x_t, t, y_emb)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/guillaume12321/Documents/GitHub/Classifier-Free-Diffusion-Models/src/models/unet.py", line 294, in forward
    out = torch.cat((out, buf), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 7 for tensor number 1 in the list.